version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ticket_db
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
#    volumes:
#      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql